### ISSUE TITLE
Load model and continue training

### ISSUE THREAD

**Issue by sofiafernandescd** [AliNajafi1998/ComStream#5]
Is there a way to continue training?
I saw that the part where the model is saved was commented in your code, so I uncommented it, saved a model a loaded it with the load_model( ) method, but when I call the method train( ), it starts to train from the beginning.
Am I missing something? Or is the feature not implemented?
Thanks a lot!

**Comment by AliNajafi1998** [comment]
Hi,

For loading the model you can use [load_model](https://github.com/AliNajafi1998/ComStream/blob/4ee43dd3923d774c7aa319ebe79768fbc9eb445b/ComStream/labse/Coordinator.py#L326) method, however, after loading if you use ```train``` method everything would be restarted.
To solve this issue, you need to comment [init_agents](https://github.com/AliNajafi1998/ComStream/blob/4ee43dd3923d774c7aa319ebe79768fbc9eb445b/ComStream/labse/Coordinator.py#L230) line.

The best practice would be to get an argument as ```start_mode``` for ```train``` method and check if it is the start_mode is True or False. If it was False, don't call ```init_agents``` method.
Please test it and if everything was ok, make a PR.

Best!
